server:
  port: 8082
  servlet:
    context-path: /ecommerce/api

spring:
  datasource:
    url: jdbc:postgresql://localhost:8000/order_db
    username: bojan
    password: admin
  jpa:
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create